Minor Refactor and Cleanup to prepare for Hardware Testing
OSU-AIMS/ForgeScan pull request #1
Opened 2024-10-30 13:38 UTC by acbuynak

This PR captures changes made by @bturner86239 to refine the `ForgeScan` project developed as a Master's thesis project into something usable in future projects at AIMS.

Changes included:
- Minor bug fixes
- Code styleguide compliance
- Support packages for hardware deployment and testing

⚠️ This code is UNTESTED on hardware and should be used with caution. ⚠️

2024-10-30 14:01 UTC, BSwick7 commented on src/CMakeLists.txt
> +        FORGE_SCAN_MESHES_DIR="/home/bturner86239/forgescan_ws/ForgeScan/share/Meshes"
Consider changing to relative paths, e.g., `${CMAKE_CURRENT_SOURCE_DIR}/../share`

2024-10-30 14:02 UTC, BSwick7 commented on src/Examples/Scene/main.cpp
> +    std::filesystem::path fpath = parser.get<std::filesystem::path>("--save", FORGE_SCAN_SHARE_DIR "/Examples/Scene.h5");
Using `.h5` extension here and `.hdf5` elsewhere, should this be changed?

2024-10-30 14:11 UTC, BSwick7 commented on ForgeScan/src/Examples/cmake_install.cmake
> +  set(CMAKE_INSTALL_PREFIX "/home/bturner86239/forgescan_ws/install/ForgeScan")
Make path relative to work for other users

2024-10-30 14:11 UTC, BSwick7 commented on ForgeScan/src/Examples/cmake_install.cmake
> +  include("/home/bturner86239/forgescan_ws/src/ForgeScan/src/Examples/Scene/cmake_install.cmake")
Should be relative paths

2024-10-30 14:11 UTC, BSwick7 commented on forgescan_realsense/CMakeLists.txt
> +add_definitions(-DFORGE_SCAN_MESHES_DIR="/home/bturner86239/forgescan_ws/ForgeScan/share/Meshes")
Relative path

2024-10-30 14:12 UTC, BSwick7 commented on forgescan_realsense/CMakeLists.txt
> +    /home/bturner86239/forgescan_ws/src/ForgeScan/deps/HighFive/include
Make sure relative paths carry throughout

2024-10-30 14:14 UTC, BSwick7 commented on forgescan_realsense/launch/forgescan_realsense.launch.xml
> +
Add comment for this node's purpose and the remap data

2024-10-30 14:15 UTC, BSwick7 commented on forgescan_realsense/launch/forgescan_realsense.launch.xml
> +    <node pkg="realsense2_camera" exec="realsense2_camera_node">
Add comment for this node's purpose and the remap data

2024-10-30 14:21 UTC, BSwick7 commented on forgescan_realsense/src/scan_image.cpp
> +        void take_picture(const std::shared_ptr<forgescan_realsense::srv::CameraPose::Request> request,
Consider docstring for this function and maybe the class

2024-10-30 14:23 UTC, BSwick7 commented on forgescan_realsense/src/scan_manager.cpp
> +            manager->policyAdd("--set-active --type Axis --n-views 7 --n-repeat 3 --x -1.0 --y -1.0 --z -1.0 --seed 50 --uniform");
Comments for the purpose of manager and what 'policy' is

2024-10-30 14:30 UTC, BSwick7 commented on forgescan_realsense/src/scan_image.cpp
>          void take_picture(const std::shared_ptr<forgescan_realsense::srv::CameraPose::Request> request,
You add a lot more to this class in commit 38eede334970abbc0917320a0a5dc7d278b12f86, could you break out parts of this function into smaller functions to improve readability?

2024-10-30 14:35 UTC, BSwick7 commented on forgescan_realsense/srv/CameraPose.srv
> +int64 length
Why did we add length? I understand the EigenVector[] is the eigenmatrix for the camera intrinsics, but what would I use the length variable for?

2024-10-30 14:37 UTC, BSwick7 commented on motoman_gp225_support/meshes/gp225/collision/base_link.stl
Do we want to `.gitignore` files such as `.stl` and `.dae`? @acbuynak

2024-10-30 14:41 UTC, BSwick7 commented on ForgeScan/doc/Doxyfile
> +STRIP_FROM_PATH        = /home/bturner86239/forgescan_ws/src/ForgeScan/doc/../include
Relative paths throughout

2024-10-30 14:43 UTC, BSwick7 commented on forgescan_realsense/src/scan_manager.cpp
> +            std::filesystem::path save_fpath  = "/home/bturner86239/forgescan_ws/src/reconstructions";
Path

2024-10-30 14:48 UTC, BSwick7 requested changes
Recommending small changes to improve readability and reusability:
* Switch to relative paths where applicable
* Add documentation to main functions, possibly split apart functions for simpler functionality

2024-10-30 15:07 UTC, acbuynak commented on motoman_gp225_support/meshes/gp225/collision/base_link.stl
Dependent on what we want to use this repo for in the long run. IMO project repo's should not contain process output or test run files. If this is to be a upstream modular code, then sample run files could be included.. but honestly still not desirable to have as it makes the repo heavier to include in downstream projects.

Short answer.. Yes, I'd prefer to have them excluded from the repo and filetypes included on the `.gitignore`

2024-10-30 15:10 UTC, acbuynak commented
> However, I think the `motoman_gp225_support`, `motoman_ms210_support` and `motoman_resources` packages could be imported as submodules, similar to how `realsense-ros` is currently imported. Are you building upon these packages or did you simply separate them from the motoman repository?

Agreed. Motoman packages as described are already tracked in the other repos external to our org as well as local configurations specific to lab deployment are already maintained in this org. I'd suggest including instructions for pulling in relevant support files for test.. but again, these files are just development help files and should not be stored with the base code.

2024-10-30 20:25 UTC, bturner86239 commented
Note to self for continued development:
Reinstall OpenCV
https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html

2024-10-31 13:20 UTC, acbuynak commented
Can we do `realsense-ros` as a dependency and not a submodule?

2024-10-31 13:47 UTC, BSwick7 commented
I'll blame my initial wording for that, I think we should install standard dependencies supported by ROS via `rosdep` and custom dependencies or specific repository branches should be installed via `vcs import` and a `dependencies.repos` file.

2024-11-01 18:38 UTC, bturner86239 commented
After Refactor changes, ready for review. Let me know what else needs to be fixed/changed

2024-11-03 02:16 UTC, BSwick7 commented
Made some changes to the documentation to reflect dependency on Open3D and the intended ROS 2 version.

I have a few small questions to resolve before I think it's ready to merge.
1. Can we include a working example of how to use the most important function(s)? The project documentation link is broken for ForgeScan and it'd be nice to know what scripts are useful.
2. Should the `.gitignore` use `realsense-ros` instead of `realsense_ros` at [line 11](https://github.com/OSU-AIMS/ForgeScan/blob/f4037dd5f528e33e666fdaab9fce9e988c801653/.gitignore#L11)? The GitHub repository is `realsense-ros`, so the cloned repository does not currently get ignored.
3. When building the ForgeScan repository, I ran into issues with the range-based for loop used in [line 79 of Reconstruction.hpp](https://github.com/OSU-AIMS/ForgeScan/blob/f4037dd5f528e33e666fdaab9fce9e988c801653/ForgeScan/include/ForgeScan/Data/Reconstruction.hpp#L79). Specifically, I was getting what I believe is a C++ for loop issue where it threw errors because `end` and `begin` were not specified in the scope. I fixed it locally with an index based loop. Does it matter which approach we use? I'll note that the issue might be related to my Ubuntu 20.04/ROS 2 Foxy setup.

2024-11-03 18:34 UTC, BSwick7 commented
Replicated install on one of the lab PCs with ROS 2 Humble and Ubuntu 22.04 and have a few more notes: 
1. Realsense ROS appears to install as `realsense_ros` when pulled using `dependencies.repos` and Humble, so I'll consider point 2 above irrelevant. 
2. The `opencv2` rosdep doesn't seem to function properly. Were you able to install `opencv` with this or do we need separate install steps, e.g., `pip install opencv-python`?
3. Can `HighFive` be added to `dependencies.repos` to connect properly? Or will that incorrectly setup ForgeScan. If it affects the ForgeScan install, just add the `git submodule update --init --recursive` step to the `README.MD` install steps.

2024-12-05 17:38 UTC, BSwick7 commented
@bturner86239 Bumping this, can you address the above comments so we can merge? I remember you working on some install docs that may be more applicable and succinct than what I suggested.

2024-12-23 22:14 UTC, BSwick7 reviewed
Everything looks good! 

Can you include specific use of the `scan_reconstructions` routine? If it helps, think about what someone unfamiliar with the project would need to get started. See 'the curse of knowledge', this can be useful when thinking about how to communicate topics and information to others.

2024-12-23 22:14 UTC, BSwick7 commented on README.MD
> +For examples of ROS related uses, please call the run_reconstructions service from the scan_manager node.
What do you think about adding the specific ROS run/launch command (and the C++ commands)?
E.g., `ros2 run forgescan_realsense ...`

Are there files or other setup we need for the `scan_manager`?

2025-01-07 21:04 UTC, bturner86239 commented
Problem with current codebase, will no longer run due to searching for libc++.so and libc++abi.so in "/usr/lib/llvm-11/lib/" directory instead of "/usr/lib/x86_64-linux-gnu/" directory. I created a symbolic link on my machine as a temporary solution to finish PR, but will also create new issue to track down the cmake bug.

2025-01-08 19:47 UTC, bturner86239 commented
@BSwick7 Got the last change pushed, let me know if we need anything else!

2025-01-08 20:53 UTC, BSwick7 reviewed
Fix absolute paths and copyright

2025-01-08 20:53 UTC, BSwick7 commented on ForgeScan/doc/Doxyfile
> +LAYOUT_FILE            = /home/bturner86239/forgescan_ws/src/ForgeScan/doc/DoxygenLayout.xml
Relative path

2025-01-08 20:53 UTC, BSwick7 commented on ForgeScan/doc/Doxyfile
> +                         /home/bturner86239/forgescan_ws/src/ForgeScan/doc/../README.md
Relative path

2025-01-08 20:53 UTC, BSwick7 commented on ForgeScan/doc/Doxyfile
> +USE_MDFILE_AS_MAINPAGE = /home/bturner86239/forgescan_ws/src/ForgeScan/doc/../README.md
Path

2025-01-08 20:53 UTC, BSwick7 commented on ForgeScan/doc/Doxyfile
> +HTML_EXTRA_STYLESHEET  = /home/bturner86239/forgescan_ws/src/ForgeScan/doc/doxygen-awesome-css/doxygen-awesome.css
Path

2025-01-08 20:53 UTC, BSwick7 commented on ForgeScan/src/CMakeLists.txt
> +        FORGE_SCAN_MESHES_DIR="/home/bturner86239/forgescan_ws/src/ForgeScan/share/Meshes"
Path

2025-01-08 20:53 UTC, BSwick7 commented on forgescan_realsense/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Finish filling out copyright

2025-01-08 20:53 UTC, BSwick7 commented on forgescan_support/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Copyright

2025-01-08 21:37 UTC, merged